jerryjudymary/renDevSQL

- controller/user.controller.js
- middlewares/authMiddleware.js
Docs: authMiddleware DB 커넥션 부분 수정
> Docs: authMiddleware DB 커넥션 부분 수정

- package-lock.json
- package.json
- routes/projects.js
Docs: projects 수정 - users, projects 정상 연동, package.json에 moment 모듈 추가
> Docs: projects 수정 - users, projects 정상 연동, package.json에 moment 모듈 추가

- routes/projects.js
- routes/resumes.js
Docs: 최종 test용 API 디버깅 완료, GET 메서드 관련 로직 수정.
> Docs: 최종 test용 API 디버깅 완료, GET 메서드 관련 로직 수정.

- routes/projects.js
Docs: projects API 관련 불필요한 코드 제거
> Docs: projects API 관련 불필요한 코드 제거

- models/project.js
- routes/projects.js
Docs: 프로젝트 등록 / 수정시 schedule 항목 검증 실패시 예외처리, 유효성 검사시 role 속성값 공백 허용으로 수정
> Docs: 프로젝트 등록 / 수정시 schedule 항목 검증 실패시 예외처리, 유효성 검사시 role 속성값 공백 허용으로 수정

- models/application.js
- models/project.js
- models/projectphoto.js
- models/projectskill.js
- models/user.js
- routes/projects.js
Docs: 정규화와 ORM 사용에 따른 projects API 로직 변경과 모델 파일 다수 수정
> Docs: 정규화와 ORM 사용에 따른 projects API 로직 변경과 모델 파일 다수 수정

- models/user.js
Docs: User 모델 timestamps: false 설정
> Docs: User 모델 timestamps: false 설정

- app.js
- controller/projectValidation.controller.js
- routes/applications.js
- routes/projects.js
Docs: projectVallidation.controller 파일에서 schedule 배열 형식으로 수정
> Docs: projectVallidation.controller 파일에서 schedule 배열 형식으로 수정

- controller/user.controller.js
- controller/validation.controller.js
> Docs: user 관련 파일 복구

- routes/applications.js
- routes/projects.js
Docs: 면접 예약시 난수 발생 추가, projects 상세조회 수정
> Docs: 면접 예약시 난수 발생 추가, projects 상세조회 수정

- app.js
- controller/projectValidation.controller.js
- routes/applications.js
- routes/projects.js
Docs: 면접 예약관리 API 이메일 연동 확인 - 1차 완성, 지원서 선택 목록 조회 API 추가, 면접 코드 UUID로 변경, 기존 코드 리팩토링 (early return 사용), 예외처리 추가
> Docs: 면접 예약관리 API 이메일 연동 확인 - 1차 완성, 지원서 선택 목록 조회 API 추가, 면접 코드 UUID로 변경, 기존 코드 리팩토링 (early return 사용), 예외처리 추가

- routes/projects.js
Docs: projects 수정, 삭제시 S3 다중 이미지 수정, 삭제
> Docs: projects 수정, 삭제시 S3 다중 이미지 수정, 삭제

- routes/applications.js
- routes/projects.js
Docs: 와이어프레임에 따라 프로젝트 수정부분 phone, email 삭제
> Docs: 와이어프레임에 따라 프로젝트 수정부분 phone, email 삭제

- models/project.js
- routes/projects.js
Docs: projects API 명세에 맞게 수정, project 모델에서 phone 컬럼 제거
> Docs: projects API 명세에 맞게 수정, project 모델에서 phone 컬럼 제거

- routes/projects.js
> Docs: projects 예외처리 수정

- package-lock.json
- package.json
- routes/projects.js
Docs: projects 관련 - 프로젝트 수정시 schedule 제외, 이미지 선별 삭제 로직 추가, 이미지 업로드 URL 중복 방지용으로  Date.now -> UUID 변경
package.json 관련 - uuid 라이브러리 추가
> Docs: projects 관련 - 프로젝트 수정시 schedule 제외, 이미지 선별 삭제 로직 추가, 이미지 업로드 URL 중복 방지용으로  Date.now -> UUID 변경 package.json 관련 - uuid 라이브러리 추가

- routes/projects.js
> Docs: projects 시간 재조정

- app.js
- models/project.js
- models/proposal.js
- models/resume.js
- routes/applications.js
- routes/notices.js
- routes/projects.js
- routes/proposals.js
Feat: 면접 제안 API, 모델 추가
Docs: app.js상 proposal 관련 항목 추가, 면접 예약시 지원서 조회 수정, 기타 모델 종속관계 수정, 테이블 변경에 따른 notices 변수면 변경
> Feat: 면접 제안 API, 모델 추가 Docs: app.js상 proposal 관련 항목 추가, 면접 예약시 지원서 조회 수정, 기타 모델 종속관계 수정, 테이블 변경에 따른 notices 변수면 변경

- routes/projects.js
> Docs: 오타 수정

- config/config.js
- models/index.js
Docs: config.json -> config.js로 변경, model index.js 수정
> Docs: config.json -> config.js로 변경, model index.js 수정

- routes/projects.js
> Docs: projects 예외처리 순서, 문구 수정

- routes/projects.js
Docs: projects 예외처리 추가 - 전체조회 시 단 하나의 프로젝트도 존재하지 않을 경우
> Docs: projects 예외처리 추가 - 전체조회 시 단 하나의 프로젝트도 존재하지 않을 경우

- routes/applications.js
> Docs: applicaitons 예외처리 수정

- routes/proposals.js
> Docs: proposals 예외처리 추가

- config/redis.js
- routes/projects.js
Feat: projects 라우터 캐싱(Look - aside) 적용, Redis 설정 파일 추가.
> Feat: projects 라우터 캐싱(Look - aside) 적용, Redis 설정 파일 추가.

- routes/projects.js
> Docs: projects 수정

- .gitignore
- app.js
- index.js
- package-lock.json
- package.json
- test/integtests/projects.spec.js
Feat: 테스트코드 폴더 생성, supertest를 위한 서버 listening 분리
> Feat: 테스트코드 폴더 생성, supertest를 위한 서버 listening 분리

- routes/projects.js
- routes/resumes.js
Feat: resumes 조회 전반 Redis 캐싱 추가
> Feat: resumes 조회 전반 Redis 캐싱 추가

- config/config.js
- config/database.js
- index.js
Docs: 개발 테스트용 DB로 연동되도록 sequelize / mysql 설정파일 수정
> Docs: 개발 테스트용 DB로 연동되도록 sequelize / mysql 설정파일 수정

- config/redis.js
Feat: Redis DB(index) 설정 추가 (주석과 노션을 참고해 주세요)
> Feat: Redis DB(index) 설정 추가 (주석과 노션을 참고해 주세요)

- routes/resumes.js
Docs: 트러블슈팅을 위한 resumes 레디스 제거
> Docs: 트러블슈팅을 위한 resumes 레디스 제거

- routes/projects.js
> Docs: projects 프라미스 체이닝 수정

- routes/projects.js
Reverts jerryjudymary/renDevSQL#99
> Revert "Docs: projects 프라미스 체이닝 수정"

- config/config.js
- config/redis.js
Docs: MySQL, Redis config 실 서버로 변경
> Docs: MySQL, Redis config 실 서버로 변경

- config/config.js
> Docs: config DB 수정

- API/projects/controllers/project.controller.js
- API/projects/controllers/projectValidation.controller.js
Docs: 프론트단 요청으로 projects 날짜 유효성 관련 항목 수정
> Docs: 프론트단 요청으로 projects 날짜 유효성 관련 항목 수정

- API/applications/controllers/applications.controller.js
- API/applications/index.js
- API/projects/controllers/project.controller.js
Feat: applications 인터뷰 완료, 매칭 완료, 마감기능 API 추가, Docs: applications API URI 엔드포인트 수정
> Feat: applications 인터뷰 완료, 매칭 완료, 마감기능 API 추가, Docs: applications API URI 엔드포인트 수정

- API/projects/controllers/project.controller.js
Docs: projects 전체, 상세조회 관련 raw query 전환으로 복잡도 개선
> Docs: projects 전체, 상세조회 관련 raw query 전환으로 복잡도 개선

- API/projects/controllers/project.controller.js
> Docs: projects 쿼리 세부사항 수정

- API/projects/controllers/project.controller.js
> Docs: projects 상세조회 Redis 수정

- API/search/controllers/search.controller.js
> Docs : req.body 로 코드 수정

- API/projects/controllers/project.controller.js
- API/projects/controllers/projectValidation.controller.js
Feat: proejcts 수정 파트에 예약 수정 기능 추가, FE단 요청으로 시간 형식 변환 추가
> Feat: proejcts 수정 파트에 예약 수정 기능 추가, FE단 요청으로 시간 형식 변환 추가

- API/projects/controllers/project.controller.js
- API/projects/controllers/projectValidation.controller.js
Docs: projects 등록 시 photos 유효성 검사 관련 수정
> Docs: projects 등록 시 photos 유효성 검사 관련 수정

- API/projects/controllers/project.controller.js
Docs: projects 등록 - 수정 트랜잭션 커밋 위치, 예외처리, 시간대 수정
> Docs: projects 등록 - 수정 트랜잭션 커밋 위치, 예외처리, 시간대 수정

- API/projects/controllers/project.controller.js
Docs: projects 기능 전반 Redis 키 삭제 위치 변경
> Docs: projects 기능 전반 Redis 키 삭제 위치 변경

- API/projects/controllers/project.controller.js
> Docs: projects Redis 위치 복구

- API/resumes/controllers/resume.controller.js
> Feat: resumes 조회 전반 레디스 캐싱 추가

- API/resumes/controllers/resume.controller.js
> Docs: resumes 상세조회 Redis 수정

- API/proposals/controllers/proposal.controller.js
> Docs: 면접 제안 이메일 발송 문구 수정

- API/projects/controllers/project.controller.js
- API/resumes/controllers/resume.controller.js
- config/redis.js
- config/redis_modules.js
- test/integration/projects.spec.js
Docs: TCPWRAP 관련 Redis 모듈화 구조 변경, projects CRUD 테스트 커버리지 작성
> Docs: TCPWRAP 관련 Redis 모듈화 구조 변경, projects CRUD 테스트 커버리지 작성

- API/projects/controllers/project.controller.js
Docs: projects 상세조회에 해당 유저 profileImage 항목 추가
> Docs: projects 상세조회에 해당 유저 profileImage 항목 추가

- API/projects/controllers/project.controller.js
Docs: project 등록시 schedule 예외처리 추가
> Docs: project 등록시 schedule 예외처리 추가

- API/applications/controllers/applications.controller.js
- API/projects/controllers/project.controller.js
Docs: 면접 예약시 해당 projectId 캐시 삭제
> Docs: 면접 예약시 해당 projectId 캐시 삭제

- test/integration/users.spec.js
Docs: 회원관리 테스트 코드 수정 - 이메일 인증 추가, 컬럼 삭제에 따른 변경사항 반영
> Docs: 회원관리 테스트 코드 수정 - 이메일 인증 추가, 컬럼 삭제에 따른 변경사항 반영

- API/projects/controllers/project.controller.js
- config/redis.js
- package-lock.json
- package.json
Feat: 커서 페이징과 그에 따른 캐싱 로직 업데이트 (프론트 구현 전까지 주석처리), redis-delete-wildcard 모듈 설치 관련 업데이트
> Feat: 커서 페이징과 그에 따른 캐싱 로직 업데이트 (프론트 구현 전까지 주석처리), redis-delete-wildcard 모듈 설치 관련 업데이트
